import requests
import json

token = "eyJhbGciOiJFUzI1NiIsImtpZCI6IjAxNDRkZGRmLTIxOWUtNGMyZC1iOGRlLWViMmFlZDZmNTk3ZCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nja3puamt6c2Z5cHNzZ2VjeXlhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyZWIyMjRlYi0xYTVmLTQxMTItODY3YS1lZDE5ODRhZDA2ODciLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzczNTEzNTgwLCJpYXQiOjE3NzM1MDk5ODAsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwib25ib2FyZGluZ19jb21wbGV0ZWQiOnRydWUsIm9uYm9hcmRpbmdfY29tcGxldGVkX2F0IjoiMjAyNi0wMy0xNFQxMTowMzoxNC43OTZaIiwib25ib2FyZGluZ19wcm9maWxlIjp7ImFpX2ZydXN0cmF0aW9uIjoicmVwZWF0cyIsImF1ZGllbmNlIjoidGVjaG5pY2FsIiwiZnJ1c3RyYXRpb25fZGV0YWlsIjoiIiwicHJpbWFyeV91c2UiOiJjb2RpbmcifSwib25ib2FyZGluZ19wcm9maWxlX3NldF9hdCI6IjIwMjYtMDMtMTRUMTE6MDM6MTMuNjcyWiIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiMmViMjI0ZWItMWE1Zi00MTEyLTg2N2EtZWQxOTg0YWQwNjg3IiwidGVybXNfYWNjZXB0ZWQiOnRydWUsInRlcm1zX2FjY2VwdGVkX2F0IjoiMjAyNi0wMy0xNFQxMTowMTo1Ny43NjVaIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzM0ODYxMDF9XSwic2Vzc2lvbl9pZCI6IjBjZWMzMmRkLTMzODktNGEwNi1hZjRkLWUzNDRlZThlZTdmOCIsImlzX2Fub255bW91cyI6ZmFsc2V9.RA4aSfoVONialQWa_sU1ReA7BNFssEcCqWlReXSyEkPJX_8JyZBObwVQernx7FEZMlRtmedvDKp-2g1F7GB4sA"

url = "http://localhost:8000/sessions"
headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json",
    "Origin": "http://localhost:3000"
}

print(f"Calling {url}...")
try:
    response = requests.get(url, headers=headers)
    print(f"Status Code: {response.status_code}")
    print(f"Response: {response.text}")
except Exception as e:
    print(f"Error: {e}")
